def checkA(s)
  result = ""
  s.split(" ").each do |s|
    case s
      when ".-"
        result += "A"
      when "-..."
        result += "B"
      when "-.-."
        result += "C"
      when "-.."
        result += "D"
      when "."
        result += "E"
      when "..-."
        result += "F"
      when "--."
        result += "G"
      when "...."
        result += "H"
      when ".."
        result += "I"
      when ".---"
        result += "J"
      when "-.-"
        result += "K"
      when ".-.."
        result += "L"
      when "--"
        result += "M"
      when "-."
        result += "N"
      when "---"
        result += "O"
      when ".--."
        result += "P"
      when "--.-"
        result += "Q"
      when ".-."
        result += "R"
      when "..."
        result += "S"
      when "-"
        result += "T"
      when "..-"
        result += "U"
      when "...-"
        result += "V"
      when ".--"
        result += "W"
      when "-..-"
        result += "X"
      when "-.--"
        result += "Y"
      when "--.."
        result += "Z"
      else
        result += " "
    end
  end
  return result + " "
end

INPUT = ".-   -... --- -..-   ..-. ..- .-.. .-..   --- ..-.   .-. ..- -... .. . ..."
output = ""
INPUT.split("   ").each do |s|
  output += checkA(s)
end
puts output